/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufu.sd.client.ui;

import br.ufu.sd.client.HashTableApi;
import br.ufu.sd.grpc.Saida;
import com.google.protobuf.ByteString;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Giullia
 */
public class Cadastrar extends javax.swing.JFrame {
    
    private HashTableApi client;
    /**
     * Creates new form Cadastrar
     */
    
    public Cadastrar(HashTableApi client) {
        initComponents();
        this.client = client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_text_chave = new javax.swing.JTextField();
        j_text_dado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_cadastro_efetuado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_text_chave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_text_chaveActionPerformed(evt);
            }
        });

        j_text_dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_text_dadoActionPerformed(evt);
            }
        });

        jLabel1.setText("CHAVE:");

        jLabel2.setText("DADO:");

        jLabel4.setMinimumSize(new java.awt.Dimension(200, 200));

        jButton_cadastro_efetuado.setText("CADASTRAR");
        jButton_cadastro_efetuado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastro_efetuadoActionPerformed(evt);
            }
        });

        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1)
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_cadastro_efetuado)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j_text_dado)
                            .addComponent(j_text_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_text_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_text_dado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addComponent(jButton_cadastro_efetuado)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_text_chaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_text_chaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_text_chaveActionPerformed

    private void jButton_cadastro_efetuadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastro_efetuadoActionPerformed
        Saida saida;
        String texto;
        ByteString dado = ByteString.copyFrom(j_text_dado.getText().getBytes());
        long chave = (long) Integer.parseInt(j_text_chave.getText());
        //JOptionPane.showMessageDialog(this, chave);
        saida = this.client.set(chave, dado);
        if(saida == null){
            texto = "Um erro insesperado aconteceu";
        }
        else if(saida.getValue().getTimeSt() == 0){
            texto = "A chave " + chave + " foi inserida no banco";
        }else{
            texto = "A valor abaixo foi deletado\n"
                    + saida.getValue().getVersion() + "\n"
                    + new Date(saida.getValue().getTimeSt()) + "\n"
                    + saida.getValue().getData().toStringUtf8();
        }
        JOptionPane.showMessageDialog(this,texto);
    }//GEN-LAST:event_jButton_cadastro_efetuadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu(this.client).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j_text_dadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_text_dadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_text_dadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cadastro_efetuado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField j_text_chave;
    private javax.swing.JTextField j_text_dado;
    // End of variables declaration//GEN-END:variables
}
